port 26379
bind 0.0.0.0
protected-mode no
dir /data

sentinel monitor mymaster redis-1 6379 3
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
