{{- if eq .Values.workload "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rsr.fullname" . }}
  labels:
    {{- include "rsr.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rsr.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "rsr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rsr.labels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: reconciler
          image: "{{ include "rsr.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            {{- if .Values.sentinelFromOrdinal.enabled }}
            - --sentinel-from-ordinal-prefix={{ .Values.sentinelFromOrdinal.prefix }}
            - --sentinel-from-ordinal-suffix={{ .Values.sentinelFromOrdinal.suffix }}
            {{- else if .Values.sentinelAddr }}
            - --sentinel-addr={{ .Values.sentinelAddr }}
            {{- end }}
            {{- include "rsr.commonArgs" . | nindent 12 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- include "rsr.authEnv" . | nindent 12 }}
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
