#!/bin/sh
set -e
if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
	systemctl stop redis-sentinel-reconciler >/dev/null 2>&1 || true
	systemctl disable redis-sentinel-reconciler >/dev/null 2>&1 || true
fi
