bind 0.0.0.0
port 0
tls-port 6379
tls-cert-file /tls/redis.lab.pem
tls-key-file /tls/redis.lab-key.pem
tls-ca-cert-file /tls/ca.pem
tls-auth-clients no
tls-replication yes
protected-mode no
appendonly no
dir /data
