port 0
tls-port 26379
tls-cert-file /tls/sentinel.lab.pem
tls-key-file /tls/sentinel.lab-key.pem
tls-ca-cert-file /tls/ca.pem
tls-auth-clients no
tls-replication yes
bind 0.0.0.0
protected-mode no
dir /data

sentinel resolve-hostnames yes
sentinel monitor mymaster redis.lab 6379 1
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
